// Generated by CoffeeScript 1.8.0
var ApplicationController, girls_helpers, path;

path = require('path');

girls_helpers = require(path.resolve('app/helpers/girls'));

ApplicationController = require(path.resolve('app/controllers/application'));

module.exports = function(app) {
  var application;
  application = new ApplicationController();
  app.get('/admin', application.allow_only_admin, application.admin);
  return app.get('/', girls_helpers, application.index);
};
