// Generated by CoffeeScript 1.8.0
var FilesController, path;

path = require('path');

FilesController = require(path.resolve('app/controllers/files'));

module.exports = function(app) {
  var files;
  files = new FilesController();
  return app["delete"]('/files/:id', files.allow_only_admin, files.destroy);
};
