// Generated by CoffeeScript 1.8.0
var FilesController, multipart, path;

path = require('path');

multipart = require('connect-multiparty');

FilesController = require(path.resolve('app/controllers/files'));

multipart = multipart({
  maxFieldsSize: 1024 * 1024 * 20,
  uploadDir: path.resolve('public/files')
});

module.exports = function(app) {
  var files;
  files = new FilesController();
  return app["delete"]('/files/:id', files.allow_only_admin, files.destroy);
};
