// Generated by CoffeeScript 1.8.0
var routes, _;

_ = require('underscore');

routes = ['application', 'categories', 'girls', 'sessions', 'slides'];

module.exports = function(app) {
  return _.each(routes, function(route) {
    return require("./" + route)(app);
  });
};
