// Generated by CoffeeScript 1.8.0
var SessionsController, path;

path = require('path');

SessionsController = require(path.resolve('app/controllers/sessions'));

module.exports = function(app) {
  var sessions;
  sessions = new SessionsController();
  app.post('/sessions', sessions.create);
  app.get('/sessions/new', sessions.create_show);
  return app["delete"]('/sessions/logout', sessions.destroy);
};
