// Generated by CoffeeScript 1.8.0
var SlidesController, multipart, path;

path = require('path');

multipart = require('connect-multiparty');

SlidesController = require(path.resolve('app/controllers/slides'));

multipart = multipart({
  maxFieldsSize: 1024 * 1024 * 20,
  uploadDir: path.resolve('public/files')
});

module.exports = function(app) {
  var slides;
  slides = new SlidesController();
  app.get('/slides', slides.index);
  app.post('/slides', slides.allow_only_admin, multipart, slides.create);
  return app["delete"]('/slides/:id', slides.allow_only_admin, slides.destroy);
};
