// Generated by CoffeeScript 1.8.0
var SlidesController, path;

path = require('path');

SlidesController = require(path.resolve('app/controllers/slides'));

module.exports = function(app) {
  var slides;
  slides = new SlidesController();
  app.post('/slides', slides.allow_only_admin, slides.create);
  return app["delete"]('/slides/:id', slides.allow_only_admin, slides.destroy);
};
