// Generated by CoffeeScript 1.8.0
var database, env, path, secrets, _, _ref, _settings;

_ = require('underscore');

path = require('path');

env = process.env.NODE_ENV;

secrets = require('./config.secure.json');

database = require('./database.json');

_settings = require('./settings.json');

_ref = [_settings, database].map(function(conf) {
  return conf[env] || conf["default"];
}), _settings = _ref[0], database = _ref[1];

global.settings = _settings;

settings.database = _.extend(database, secrets[database.protocol]);

settings.memcached = secrets.memcached;

_.each(_settings, function(value, key) {
  settings.__defineGetter__(key, function() {
    return value;
  });
  return settings.__defineSetter__(key, function() {
    throw new Error("Changing settings." + key + " is deprecated");
  });
});
