// Generated by CoffeeScript 1.8.0
var get_categories, _;

_ = require('underscore');

get_categories = function(girl) {
  var _ref;
  if (!((_ref = girl.categories) != null ? _ref.length : void 0)) {
    return [];
  }
  return _.map(girl.categories, function(category) {
    return "category-id-" + category.category_id;
  });
};

module.exports = function(req, res, next) {
  res.locals.girls_helpers = {
    get_categories: get_categories
  };
  return next();
};
