// Generated by CoffeeScript 1.8.0
var get_categories, get_main_photo, _;

_ = require('underscore');

get_categories = function(girl) {
  var _ref;
  if (!((_ref = girl.categories) != null ? _ref.length : void 0)) {
    return [];
  }
  return _.map(girl.categories, function(category) {
    return "category-" + category.category_id;
  });
};

get_main_photo = function(girl) {
  var main;
  main = _.find(girl.files, function(file) {
    return file.is_main;
  });
  return main != null ? main.path : void 0;
};

module.exports = function(req, res, next) {
  res.locals.girls_helpers = {
    get_categories: get_categories,
    get_main_photo: get_main_photo
  };
  return next();
};
