// Generated by CoffeeScript 1.8.0
var ApplicationController, async, orm,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

orm = require('node-orm');

async = require('async');

module.exports = ApplicationController = (function() {
  var Categories, Girls;

  function ApplicationController() {
    this.allow_only_admin = __bind(this.allow_only_admin, this);
  }

  Categories = orm.models.category;

  Girls = orm.models.girl;

  ApplicationController.prototype.check_is_authenticated = function(req, res, next) {
    if (!req.session.user) {
      req.session.wanted_url = req.url;
      return res.redirect('/sessions/new');
    } else {
      return next();
    }
  };

  ApplicationController.prototype.allow_only_admin = function(req, res, next) {
    return this.check_is_authenticated(req, res, function() {
      if (!req.session.user.is_admin) {
        return res.status(403).end();
      } else {
        return next();
      }
    });
  };

  ApplicationController.prototype.index = function(req, res) {
    res.locals.title = "MDLS'teem";
    return async.parallel({
      categories: Categories.all,
      girls: Girls.all
    }, function(err, results) {
      if (err) {
        return res.status(500).send(err.messsage || err);
      } else {
        res.locals.girls = results.girls || [];
        res.locals.categories = results.categories || [];
        return res.render('application/index');
      }
    });
  };

  ApplicationController.prototype.admin = function(req, res) {
    res.locals.title = 'ADMIN';
    return res.render('application/admin');
  };

  return ApplicationController;

})();
