// Generated by CoffeeScript 1.8.0
var ApplicationController, async, orm,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

orm = require('node-orm');

async = require('async');

module.exports = ApplicationController = (function() {
  var Categories, Files, Girls;

  function ApplicationController() {
    this.allow_only_admin = __bind(this.allow_only_admin, this);
  }

  Categories = orm.models.category;

  Girls = orm.models.girl;

  Files = orm.models.file;

  ApplicationController.prototype.check_is_authenticated = function(req, res, next) {
    if (!req.session.user) {
      req.session.wanted_url = req.url;
      return res.redirect('/sessions/new');
    } else {
      return next();
    }
  };

  ApplicationController.prototype.allow_only_admin = function(req, res, next) {
    return this.check_is_authenticated(req, res, function() {
      if (!req.session.user.is_admin) {
        return res.status(403).end();
      } else {
        return next();
      }
    });
  };

  ApplicationController.prototype.index = function(req, res) {
    res.locals.title = settings.Finder.title;
    return async.parallel({
      categories: Categories.all,
      girls: Girls.all,
      slides: Files.find({}).where("girl_id IS NULL").all
    }, function(err, results) {
      if (err) {
        return res.status(500).send(err.messsage || err);
      } else {
        res.locals.girls = results.girls || [];
        res.locals.categories = results.categories || [];
        res.locals.slides = results.slides || [];
        res.locals.socials = settings.Finder.socials;
        res.locals.description = settings.Finder.description;
        return res.render('application/index');
      }
    });
  };

  ApplicationController.prototype.admin = function(req, res) {
    res.locals.title = 'ADMIN';
    res.locals.socials = settings.Finder.socials;
    return res.render('application/admin');
  };

  ApplicationController.prototype.show = function(req, res) {
    return res.send({
      id: req.params.id,
      value: settings.Finder[req.params.id]
    });
  };

  ApplicationController.prototype.update = function(req, res) {
    settings.Finder[req.params.id] = req.param('value');
    return settings.Finder.save(function(err) {
      if (err) {
        return res.status(500).send(err.messsage || err);
      } else {
        return res.send({
          id: req.params.id,
          value: settings.Finder[req.params.id]
        });
      }
    });
  };

  return ApplicationController;

})();
