// Generated by CoffeeScript 1.8.0
var ApplicationController, CategoriesController, async, orm,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

orm = require('node-orm');

async = require('async');

ApplicationController = require('./application');

module.exports = CategoriesController = (function(_super) {
  var Categories;

  __extends(CategoriesController, _super);

  function CategoriesController() {
    return CategoriesController.__super__.constructor.apply(this, arguments);
  }

  Categories = orm.models.category;

  CategoriesController.prototype.index = function(req, res) {
    return Categories.all(function(err, categories) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.send(categories);
      }
    });
  };

  CategoriesController.prototype.create = function(req, res) {
    var name;
    name = req.param('name');
    if (!(typeof name === 'string' && name !== '')) {
      res.status(400).end();
      return;
    }
    return Categories.create({
      name: name
    }, function(err, category) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.send(category);
      }
    });
  };

  CategoriesController.prototype.update = function(req, res) {
    var name;
    name = req.param('name');
    if (!(typeof name === 'string' && name !== '')) {
      res.status(400).end();
      return;
    }
    return async.waterfall([
      function(next) {
        return Categories.one({
          category_id: req.params.id
        }, next);
      }, function(category, next) {
        if (!category) {
          return next(new Error("Can't find category"));
        } else {
          category.name = name;
          return category.save(next);
        }
      }
    ], function(err, category) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.send(category);
      }
    });
  };

  CategoriesController.prototype.destroy = function(req, res) {
    return async.waterfall([
      function(next) {
        return Categories.one({
          category_id: req.params.id
        }, next);
      }, function(category, next) {
        if (!category) {
          return next(new Error("Can't find category"));
        } else {
          return category.remove(next);
        }
      }
    ], function(err) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.end();
      }
    });
  };

  return CategoriesController;

})(ApplicationController);
