// Generated by CoffeeScript 1.8.0
var ApplicationController, FilesController, async, fs, orm, path, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

orm = require('node-orm');

async = require('async');

_ = require('underscore');

path = require('path');

fs = require('fs');

ApplicationController = require('./application');

module.exports = FilesController = (function(_super) {
  var Files;

  __extends(FilesController, _super);

  function FilesController() {
    return FilesController.__super__.constructor.apply(this, arguments);
  }

  Files = orm.models.file;

  FilesController.prototype.destroy = function(req, res) {
    return async.waterfall([
      function(next) {
        return Files.get(req.params.id, next);
      }, function(file, next) {
        if (!file) {
          return next(new Error("Can't find file"));
        } else {
          return file.remove(next);
        }
      }
    ], function(err) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.end();
      }
    });
  };

  return FilesController;

})(ApplicationController);
