// Generated by CoffeeScript 1.8.0
var SessionsController, orm;

orm = require('node-orm');

module.exports = SessionsController = (function() {
  var User;

  function SessionsController() {}

  User = orm.models.user;

  SessionsController.prototype.create_show = function(req, res) {
    var root, url, user;
    user = req.session.user;
    if (user) {
      root = user.is_admin ? '/admin' : '/';
      url = req.session.wanted_url;
      if (url === '/sessions/new' || !url) {
        url = root;
      }
      return res.redirect(url);
    } else {
      res.locals.title = "MDLS'teem login";
      return res.render('sessions/new');
    }
  };

  SessionsController.prototype.create = function(req, res) {
    var email, password;
    email = req.body.email;
    password = req.body.password;
    if (!((email != null) && (password != null))) {
      res.render('sessions/new', {
        message: 'Parameters email or/and password are missed'
      });
      return;
    }
    return new User({
      email: email,
      password: password
    }).login(function(err, user) {
      var root, url;
      if (err) {
        logger.warn(err);
        return res.render('sessions/new', {
          message: err.message || err
        });
      } else {
        root = user.is_admin ? '/admin' : '/';
        url = req.session.wanted_url || root;
        req.session.user = user;
        if (url === '/favicon.ico') {
          url = root;
        }
        return res.redirect(url);
      }
    });
  };

  SessionsController.prototype.destroy = function(req, res) {
    req.session.destroy();
    return res.redirect('/sessions/new');
  };

  return SessionsController;

})();
