// Generated by CoffeeScript 1.8.0
var ApplicationController, SliderController, async, fs,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

async = require('async');

fs = require('fs');

ApplicationController = require('./application');

module.exports = SliderController = (function(_super) {
  __extends(SliderController, _super);

  function SliderController() {
    return SliderController.__super__.constructor.apply(this, arguments);
  }

  SliderController.prototype.create = function(req, res) {
    var name;
    name = req.param('name');
    if (!(typeof name === 'string' && name !== '')) {
      res.status(400).end();
      return;
    }
    return Slider.create({
      name: name
    }, function(err, category) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.send(category);
      }
    });
  };

  SliderController.prototype.destroy = function(req, res) {
    return async.waterfall([
      function(next) {
        return Slider.one({
          category_id: req.params.id
        }, next);
      }, function(category, next) {
        if (!category) {
          return next(new Error("Can't find category"));
        } else {
          return category.remove(next);
        }
      }
    ], function(err) {
      if (err) {
        return res.status(500).send(err.message || err);
      } else {
        return res.end();
      }
    });
  };

  return SliderController;

})(ApplicationController);
