// Generated by CoffeeScript 1.8.0
var async, _;

_ = require('underscore');

async = require('async');

module.exports = function(db) {
  var Categories;
  Categories = db.define('category', {
    category_id: {
      type: 'serial',
      key: true
    },
    name: {
      type: 'text',
      size: 100
    }
  }, {
    methods: {}
  });
  return Categories.hasMany('girls', db.models.girl, {}, {
    autoFetch: true,
    mergeTable: 'girl_to_category',
    getAccessor: 'get_girls'
  });
};
