// Generated by CoffeeScript 1.8.0
var fd, _;

_ = require('underscore');

fd = require('fs');

module.exports = function(db) {
  var Files;
  Files = db.define('file', {
    file_id: {
      type: 'serial',
      key: true
    },
    path: {
      type: 'text'
    },
    size: {
      type: 'integer',
      size: 8
    },
    type: {
      type: 'enum',
      values: ['photo', 'video']
    }
  }, {
    hooks: {
      afterRemove: function(callback) {
        return fs.unlink(this.path, callback);
      }
    }
  });
  return Files.hasOne('girl', db.models.girl, {}, {
    autoFetch: true,
    reverse: "files"
  });
};
