// Generated by CoffeeScript 1.8.0
var fs, path, _;

_ = require('underscore');

path = require('path');

fs = require('fs');

module.exports = function(db) {
  var Files;
  Files = db.define('file', {
    file_id: {
      type: 'serial',
      key: true
    },
    path: {
      type: 'text'
    },
    size: {
      type: 'integer',
      size: 8
    },
    type: {
      type: 'enum',
      values: ['photo', 'video']
    },
    is_main: {
      type: 'boolean',
      "default": false
    }
  }, {
    hooks: {
      beforeRemove: function(callback) {
        var true_path;
        true_path = this.path.replace(/^\/static/, path.resolve('public'));
        return fs.unlink(true_path, callback);
      }
    }
  });
  return Files.hasOne('girl', db.models.girl, {}, {
    field: 'girl_id',
    autoFetch: true,
    autoFetchLimit: 2,
    reverse: "files"
  });
};
