// Generated by CoffeeScript 1.8.0
var Finder, finder_path, fs, path, _;

_ = require('underscore');

fs = require('fs');

path = require('path');

finder_path = path.resolve('config/local.finder.json');

Finder = require(finder_path);

Finder.save = function(callback) {
  var e, str;
  str = '';
  try {
    str = JSON.stringify(Finder, null, 4);
  } catch (_error) {
    e = _error;
    callback(new Error("Can't stringify Finder"));
    return;
  }
  return fs.writeFile(finder_path, str, callback);
};

module.exports = Finder;
