// Generated by CoffeeScript 1.8.0
var async, _;

_ = require('underscore');

async = require('async');

module.exports = function(db) {
  var Girls;
  Girls = db.define('girl', {
    girl_id: {
      type: 'serial',
      key: true
    },
    name: {
      type: 'text',
      size: 100
    },
    description: {
      type: 'text',
      size: 1000
    },
    rating: {
      type: 'number',
      defaultValue: 0
    },
    main_photo: {
      type: 'text'
    }
  }, {
    methods: {
      add_photo: function(callback) {
        return callback();
      }
    }
  });
  return Girls.hasMany('categories', db.models.category, {}, {
    autoFetch: true,
    mergeTable: 'girl_to_category',
    getAccessor: 'get_categories'
  });
};
