// Generated by CoffeeScript 1.8.0
var async, fs, _;

_ = require('underscore');

fs = require('fs');

async = require('async');

module.exports = function(db) {
  var Girls;
  Girls = db.define('girl', {
    girl_id: {
      type: 'serial',
      key: true
    },
    name: {
      type: 'text',
      size: 100
    },
    description: {
      type: 'text',
      size: 1000
    },
    rating: {
      type: 'number',
      defaultValue: 0
    },
    profile_photo: {
      type: 'text'
    }
  }, {
    methods: {
      add_file: function(file, callback) {
        async.waterfall([]);
        return callback();
      }
    }
  });
  return Girls.hasMany('categories', db.models.category, {}, {
    autoFetch: true,
    mergeId: 'girl_id',
    mergeAssocId: 'category_id',
    mergeTable: 'girl_to_category',
    getAccessor: 'get_categories',
    setAccessor: 'set_categories'
  });
};
