// Generated by CoffeeScript 1.8.0
var async, models, orm, _;

orm = require('node-orm');

async = require('async');

_ = require('underscore');

models = [
  {
    file: 'categories',
    model_name: 'category'
  }, {
    file: 'files',
    model_name: 'file'
  }, {
    file: 'girls',
    model_name: 'girl'
  }, {
    file: 'users',
    model_name: 'user'
  }
];

module.exports = function(callback) {
  logger.debug('Connecting to DB');
  orm.settings.set('instance.cache', false);
  return orm.connect(settings.DATABASE, function(err, db) {
    if (err != null) {
      throw new Error("Can't connect to DB: " + err);
      return;
    }
    _.each(models, function(model) {
      return require("./" + model.file)(db);
    });
    orm.models = db.models;
    logger.debug('Connected');
    return callback();
  });
};
