// Generated by CoffeeScript 1.8.0
var crypto;

crypto = require('crypto');

module.exports = function(db) {
  var Users;
  return Users = db.define('user', {
    user_id: {
      type: 'serial',
      key: true
    },
    email: {
      type: 'text',
      size: 45
    },
    password: {
      type: 'text',
      size: 64
    },
    is_admin: {
      type: 'boolean',
      defaultValue: false
    }
  }, {
    methods: {
      login: function(callback) {
        var sha256;
        sha256 = crypto.createHash('sha256');
        sha256.update(this.password + settings.USER.salt);
        this.password = sha256.digest('hex');
        return Users.one({
          email: this.email,
          password: this.password
        }, function(err, user) {
          if (!err && !user) {
            err = "User wasn't found";
          }
          return callback(err, user);
        });
      }
    }
  });
};
